// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Microsoft.SemanticKernel.Connectors.Amazon;

/// <summary>
/// Provides tools accessed by the Command R execution settings and Command R request.
/// </summary>
public static class CohereCommandRTools
{
    /// <summary>
    /// Defines the required fields for chat_history.
    /// </summary>
    public sealed class ChatMessage
    {
        /// <summary>
        /// Gets or sets the role for the message.
        /// </summary>
        /// <value>
        /// Either <see langword="USER"/> or <see langword="CHATBOT"/>.
        /// </value>
        [JsonPropertyName("role")]
        public string? Role { get; set; }

        /// <summary>
        /// Gets or sets the text contents of the message.
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get; set; }
    }

    /// <summary>
    /// Describes teh JSON structure for list of texts that the model can cite to generate a more accurate reply.
    /// </summary>
    [Serializable]
    public sealed class Document
    {
        /// <summary>
        /// Gets or sets the possible key field.
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Gets or sets the possible value field.
        /// </summary>
        [JsonPropertyName("snippet")]
        public string? Snippet { get; set; }
    }

    /// <summary>
    /// Defines tool parameters.
    /// </summary>
    [Serializable]
    public sealed class Tool
    {
        /// <summary>
        /// Gets or sets the name of the tool.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the tool.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the definitions for each tool.
        /// </summary>
        [JsonPropertyName("parameter_definitions")]
        public Dictionary<string, ToolParameter> ParameterDefinitions { get; set; } = [];
    }
    /// <summary>
    /// Describes the components of each tool parameter.
    /// </summary>
    [Serializable]
    public sealed class ToolParameter
    {
        /// <summary>
        /// Gets or sets the description of the parameter.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the parameter type (for example, str or int) as described in a string.
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether this parameter is required.
        /// </summary>
        [JsonPropertyName("required")]
        public bool? Required { get; set; }
    }

    /// <summary>
    /// Defines a Cohere tool result.
    /// </summary>
    [Serializable]
    public sealed class ToolResult
    {
        /// <summary>
        /// Gets or sets the tool call.
        /// </summary>
        [JsonPropertyName("call")]
        public ToolCall? Call { get; set; }

        /// <summary>
        /// Gets or sets the outputs from the tool call.
        /// </summary>
        [JsonPropertyName("outputs")]
        public List<Dictionary<string, string>> Outputs { get; set; } = [];
    }

    /// <summary>
    /// Defines a tool call object to be passed into the tool call.
    /// </summary>
    [Serializable]
    public sealed class ToolCall
    {
        /// <summary>
        /// Gets or sets the name of the tool.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the parameters for the tool.
        /// </summary>
        [JsonPropertyName("parameters")]
        public Dictionary<string, string> Parameters { get; set; } = [];

        /// <summary>
        /// Gets or sets the tool call identifier generated by the model.
        /// </summary>
        [JsonPropertyName("generation_id")]
        public string? GenerationId { get; set; }
    }
}
