// Copyright (c) Microsoft. All rights reserved.

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.SemanticKernel.Text;

namespace Microsoft.SemanticKernel.Connectors.Amazon;

/// <summary>
/// Provides prompt execution settings for Amazon Titan Text Generation.
/// </summary>
[JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
public class AmazonTitanExecutionSettings : PromptExecutionSettings
{
    private float? _topP;
    private float? _temperature;
    private int? _maxTokenCount;
    private List<string>? _stopSequences;

    /// <summary>
    /// Gets or sets the percentile of most-likely candidates that the model considers for the next token.
    /// </summary>
    /// <value>
    /// A value between 0.0 and 1.0. The default value is 1.0.
    /// </value>
    /// <remarks>
    /// This value controls the diversity of text that the model generates.
    /// </remarks>
    [JsonPropertyName("topP")]
    public float? TopP
    {
        get => this._topP;
        set
        {
            this.ThrowIfFrozen();
            this._topP = value;
        }
    }

    /// <summary>
    /// Gets or sets a value that controls the randomness of predictions made by the model.
    /// </summary>
    /// <value>
    /// A value between 0.0 and 1.0, with 0.0 being the most deterministic and 1.0 being the most creative.
    /// </value>
    [JsonPropertyName("temperature")]
    public float? Temperature
    {
        get => this._temperature;
        set
        {
            this.ThrowIfFrozen();
            this._temperature = value;
        }
    }

    /// <summary>
    /// Gets or sets the maximum number of tokens in the generated response.
    /// </summary>
    /// <value>
    /// A value between 0 and 4096. The default is 512.
    /// </value>
    [JsonPropertyName("maxTokenCount")]
    public int? MaxTokenCount
    {
        get => this._maxTokenCount;
        set
        {
            this.ThrowIfFrozen();
            this._maxTokenCount = value;
        }
    }

    /// <summary>
    /// Gets or sets a list of stop sequences that, if generated by the model, stop the model from generating further output.
    /// </summary>
    /// <remarks>
    /// Each sequence can be up to 20 characters in length.
    /// </remarks>
    [JsonPropertyName("stopSequences")]
    public List<string>? StopSequences
    {
        get => this._stopSequences;
        set
        {
            this.ThrowIfFrozen();
            this._stopSequences = value;
        }
    }

    /// <summary>
    /// Converts PromptExecutionSettings to AmazonTitanExecutionSettings.
    /// </summary>
    /// <param name="executionSettings">The Kernel standard PromptExecutionSettings.</param>
    /// <returns>Model-specific execution settings.</returns>
    public static AmazonTitanExecutionSettings FromExecutionSettings(PromptExecutionSettings? executionSettings)
    {
        switch (executionSettings)
        {
            case null:
                return new AmazonTitanExecutionSettings();
            case AmazonTitanExecutionSettings settings:
                return settings;
        }

        var json = JsonSerializer.Serialize(executionSettings);
        return JsonSerializer.Deserialize<AmazonTitanExecutionSettings>(json, JsonOptionsCache.ReadPermissive)!;
    }
}
